spring:
  application:
    name: produit

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: test

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

